name: 'Get and cache Dependencies'
description: 'Get the dependencies via npm and cache them.'
inputs:
  caching:
    description: 'Whether to cache dependecies'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Wether cache was used'
    value: ${{ steps.set-output.outputs.used-cache}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Output value
      id: set-output
      run: |
        echo "used-cache=${{ steps.cache.outputs.cache-hit == 'true' && inputs.caching == 'true' }}" >> $GITHUB_OUTPUT
      shell: bash