name: Reusable build workflow
on:
  workflow_call:
    inputs:
      test-job:
        description: 'Testing sucsess'
        required: true
        type: string
jobs:
  build:
    if: ${{ inputs.test-job == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: |
          echo "::group::Building"
          npm run build
          echo "::endgroup::"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist